namespace NET23_GrupprojektBank.Managers.Logic
{
    public enum UserChoice
    {
        Login,
        Back,
        Logout,
        Exit,
        MakeWithdrawal,
        MakeTransfer,
        MakeLoan,
        MakeDeposit,
        ViewWelcomeMenu,
        ViewCustomerMenu,
        ViewAdminMenu,
        ViewLogs,
        ViewLockedMenu,
        ViewBalance,
        CreateBankAccount,
        CreateChecking,
        CreateSavings,
        CreateUser,
        CreateCustomer,
        CreateAdmin,
        UpdateCurrencyExchange,
        FromFile,
        FromInternet,
        Invalid,
    }
}
