namespace NET23_GrupprojektBank.Managers
{
    public enum EventStatus
    {
        LoginSuccess,
        LoginFailed,
        LoginLocked,
        CurrencyExchangeRateUpdateSuccess,
        CurrencyExchangeRateUpdateFailed,
        CheckingCreationSuccess,
        CheckingCreationFailed,
        SavingsCreationSuccess,
        SavingCreationFailed,
        TransactionSuccess,
        TransactionFailed,
        DepositSuccess,
        DepositFailed,
        WithdrawalSuccess,
        WithdrawalFailed,
        TransferSuccess,
        TransferFailed,
        LoanSuccess,
        LoanFailed,
        AccountCreationSuccess,
        AccountCreationFailed,
        AdressSuccess,
        AdressFailed,
        EmailSuccess,
        EmailFailed,
        PhoneSuccess,
        PhoneFailed,
        ContactInformationSuccess,
        ContactInformationFailed,
        InvalidInput
    }
}
